ALTER TABLE roger.webdesign ADD COLUMN contentcolor character varying(50);
ALTER TABLE roger.webdesign ADD COLUMN contentbackgroundcolor character varying(50);
ALTER TABLE roger.webdesign ADD COLUMN ctselectcolor character varying(50);
ALTER TABLE roger.webdesign ADD COLUMN ctselectbackgroundcolor character varying(50);
ALTER TABLE roger.webdesign ADD COLUMN ctselectfocuscolor character varying(50);
ALTER TABLE roger.webdesign ADD COLUMN linkcolor character varying(50);
ALTER TABLE roger.webdesign ADD COLUMN reservablehourcolor character varying(50);
ALTER TABLE roger.webdesign ADD COLUMN nonreservablehourcolor character varying(50);
ALTER TABLE roger.webdesign ADD COLUMN footercolor character varying(50);
